paths:
  uploads: uploads
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  property_1_background_position:
    type: select
    options:
      allow_create:
      allow_empty: false
      values:
        - center
        - top
        - bottom
        - left
        - left top
        - left bottom
        - right
        - right top
        - right bottom
        -
        -
      value_key:
    label: Image Position
    cascade: true
  layout:
    type: disabled
    label: Please do not change this. Thank you.
    cascade: true
data_config: {}
timezone: Etc/UTC
